In [1]:
import numpy as np 

6.7 
Generá un vector que tenga los números impares entre el 1 y el 19 inclusive usando `arange()`. Repetí el ejercicio usando `linspace()`. 
¿Qué diferencia hay en el resultado?

In [10]:
vec_arange = np.arange(1, 19, 2)
vec_linspace = np.linspace(1, 19, num=10)

In [4]:
vec_arange 

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [7]:
vec_linspace

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

Se puede explicitar otro tipo de dato usando la palabra dytpe

In [9]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

Para ordenar un vector se puede usar `np.sort()`

In [13]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

Pero quedó desordenado! porque devuelve una copia ordenada pero no modifica el original 

In [14]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

También se puede concatenar vectores: 

In [83]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

## Tamaño, dimensiones y forma de un array

In [24]:
array_ejemplo = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                            [4, 5, 6, 7]],
                           [[0 ,1 ,2, 3],
                            [4, 5, 6, 7]]])

In [78]:
ndim_array = array_ejemplo.ndim # nro dimensiones
shape_array = array_ejemplo.shape # elementos en cada eje 
size_array = array_ejemplo.size #total de elementos 3 * 2 * 4
print(ndim_array, shape_array, size_array)

3 (3, 2, 4) 24


## Cambiar la forma de un arreglo
Es una forma de cambiar la forma del array pero son variar los datos. Tener en cuenta que van a ser la misma cantidad de elementos 

In [82]:
a = np.arange(6)
b = a.reshape(3, 2)
print(a, '\n', b)

[0 1 2 3 4 5] 
 [[0 1]
 [2 3]
 [4 5]]


## Agregar un nuevo eje a un array 
Se usa `np.newaxis`

In [42]:
a = np.arange(1, 7)
a.shape

(6,)

In [80]:
vec_fila = a[np.newaxis, :] #paso a vector fila
vec_fila.shape

(1, 6)

In [81]:
vec_columna = a[:,np.newaxis] #paso a vector columna
vec_columna.shape

(6, 1)

## Indices

In [45]:
data = np.array([1,2,3])
data[1]

2

In [46]:
data[0:2]

array([1, 2])

In [47]:
data[1:]

array([2, 3])

In [48]:
data[-2:]

array([2, 3])

In [49]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [50]:
a[a < 5]

array([1, 2, 3, 4])

In [54]:
five_up = (a >= 5)
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [53]:
a[five_up] # seleccione elementos mayores o iguales a 5

array([ 5,  6,  7,  8,  9, 10, 11, 12])

con `nonzero` obtengo los indices de los elementos que cumplen sus condicion
evuelve una tupla con dos arreglos: 
- el primer arreglo es de filas
- el segundo arreglo es de columnas

In [55]:
b = np.nonzero(a < 5) 
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [56]:
lista_de_coordenadas = list(zip(b[0], b[1]))
lista_de_coordenadas # genero una lista con las coordenadas

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [57]:
a[b] # con esto selecciono los elementos

array([1, 2, 3, 4])

In [58]:
no_hay = np.nonzero(a==42)
no_hay  # si no hay devuelve un array vacio

(array([], dtype=int64), array([], dtype=int64))

## Crear arreglos usando datos existentes 

In [60]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8] # no crea una copia directamente, si lo modifico se modifica el array original
arr1

array([4, 5, 6, 7, 8])

In [62]:
arr1[2] = 98
a

array([ 1,  2,  3,  4,  5, 98,  7,  8,  9, 10])

In [66]:
# para no crear una vista, uso el copy
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b2 = a[1, :].copy()
b2

array([5, 6, 7, 8])

In [67]:
b2[2] = 344
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
b2 # modifica solo el array copiado 

array([  5,   6, 344,   8])

## Operaciones básicas 

In [76]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
print(data, ones)

[1 2] [1 1]


In [75]:

suma = data + ones
resta = data - ones 
mult = data * data
div = data / data

print(suma, resta, mult, div)

[2 3] [0 1] [1 4] [1. 1.]
